### ISSUE TITLE
JS/TS: no longer able to import after updating to 1.2.121

### ISSUE THREAD

**Issue by TheArcaneBrony** [discord-userdoccers/discord-protos#15]
`TS2307: Cannot find module discord-protos or its corresponding type declarations.`

Note: we're upgrading from 1.2.102, will attempt to identify issues on other versions

**Comment by dolfies** [comment]
Fixed. Also fixed auto-publishing. Thanks for the bug report guys
